apiVersion: v1
kind: Pod
metadata:
  name: task-api-pod
  labels:
    app: task-api
spec:
  containers:
    - name: task-api
      image: task-api:1.0
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
